export const englishLandingText = {
  "features": {
    "brandingTitle": "Custom Branding",
    "brandingDescription": "Make every transfer your own. Add your logo, background and domain for a great look.",
    "linksTitle": "Familiar Links",
    "linksDescription": "All links end with .zip - a familiar sight for people used to working with files.",
    "speedTitle": "Made for RAW and 8k",
    "speedDescription": "Gigabit speeds mean less waiting for files to send, and more time working on what matters.",
    "securityTitle": "Ultimate Trust & Security",
    "securityDescription": "All file data is stored encrypted, and the source code is fully open.",
    "sourceLink": "See the code on GitHub →",
    "eyebrow": "File-sharing for Pros",
    "titleBefore": "Look",
    "titleHighlight": "professional",
    "titleAfter": "when sharing files.",
    "description": "Your clients get a fast download page with your brand on it. Add your own domain, logo and theme."
  },
  "bento": {
    "sampleMessage": "Hi! Here are the Q4 deliverables, let me know what you think.",
    "hello": "Hey John,",
    "question": "Where should I send you the assets?",
    "reply": "Here you go:",
    "noAccount": "No need for an account :)",
    "to": "To",
    "more": "more",
    "transfer": "Transfer",
    "speedCaption": "Maximum download speed across regions",
    "requestsLabel": "Transfer Requests",
    "requestsTitle": "Receive files with a link.",
    "requestsDescription": "Create personalised upload links anyone can use to send you files. No account needed. Embed them on your site or share through email.",
    "emailLabel": "Send Files by Email",
    "emailTitle": "Send to 50 inboxes at once.",
    "emailDescription": "Email a file to up to 50 recipients in one click. Every link allows unlimited downloads, meaning no awkward conversations with your clients.",
    "speedLabel": "Speed",
    "speedTitle": "Send files at full speed.",
    "speedDescription": "Every file streams from high-speed servers worldwide, so your work gets shared without waiting.",
    "securityLabel": "Privacy & Security",
    "securityTitle": "Privacy by default.",
    "securityDescription": "Security encompasses everything we do. Every file is encrypted at rest on our servers and we never track you or sell your information.",
    "eyebrow": "Features",
    "title": "Useful features for meaningful ideas.",
    "description": "Transfer.zip comes with all features you need to share without hassle.",
    "encryption": "Encryption"
  },
  "founder": {
    "aiPromise": "train AI on your content.",
    "dataPromise": "sell your data.",
    "usersPromise": "put shareholders before users.",
    "quote": "Your files should stay yours.",
    "portrait": "Portrait photo of Robin, the creator of Transfer.zip",
    "role": "Founder of Transfer.zip",
    "secondParagraph": "In a world where your data has become the product, where companies now train AI on your content and sell your information to advertisers, we believe your files should stay yours.",
    "intro": "Transfer.zip is an independent service without shareholders to appease. We put our energy into making file transfers",
    "fast": "fast",
    "reliable": "reliable",
    "simple": "simple",
    "and": ", and ",
    "ending": ", and we keep prices low by not carrying the overhead of a large corporation.",
    "promiseBefore": "We will",
    "never": "never"
  },
  "cta": {
    "titleBefore": "Try the",
    "titleAfter": "way to send files.",
    "words": [
      "easiest",
      "fastest",
      "safest",
      "simplest",
      "ethical",
      "private"
    ],
    "description": "Thousands of people use Transfer.zip every month because they're tired of big companies overcharging. Send big files fast, for less.",
    "button": "Send large files now"
  },
  "testimonials": {
    "eyebrow": "Our Reviews",
    "users": "Users"
  },
  "faq": {
    "eyebrow": "FAQ",
    "title": "Frequently asked questions",
    "contactBefore": "Can't find what you're looking for?",
    "contactLink": "Get in touch",
    "contactAfter": " and we'll help you out."
  },
  "nav": {
    "features": "Features",
    "compare": "Compare",
    "pricing": "Pricing",
    "contact": "Contact"
  },
  "account": {
    "signIn": "Sign in",
    "createAccount": "Create Account"
  },
  "header": {
    "quick": "Quick Transfer",
    "quickDescription": "Free, end-to-end encrypted, no size limit.",
    "request": "Request Files",
    "requestDescription": "A link anyone can use to upload files to you.",
    "why": "Why choose us",
    "whyDescription": "What makes Transfer.zip different.",
    "features": "Features",
    "featuresDescription": "Everything you need to send and receive.",
    "reviews": "Reviews",
    "reviewsDescription": "What real users say about Transfer.zip.",
    "faq": "FAQ",
    "faqDescription": "Answers to the questions we get most.",
    "compare": "Compare",
    "pricing": "Pricing",
    "contact": "Contact",
    "product": "Product",
    "myTransfers": "My Transfers",
    "signIn": "Sign in",
    "createAccount": "Create Account",
    "navigation": "Global",
    "closeMenu": "Close menu",
    "openMenu": "Open menu"
  },
  "footer": {
    "logo": "Company Logo",
    "tools": "Free Tools",
    "guides": "Transfer Guides",
    "iphone": "iPhone to PC",
    "pc": "PC to PC",
    "android": "Android to PC",
    "resources": "Resources",
    "support": "Support / Contact",
    "receive": "Receive Files",
    "send": "Send Files",
    "selfHosting": "Self Hosting",
    "legal": "Legal",
    "privacy": "Privacy Policy",
    "terms": "Terms",
    "impressum": "Impressum",
    "alternatives": "Alternatives",
    "wetransferAlternative": "WeTransfer Alternative",
    "smashAlternative": "Smash Alternative",
    "comparisons": "Comparisons",
    "wetransferComparison": "Transfer.zip vs WeTransfer",
    "smashComparison": "Transfer.zip vs Smash",
    "made": "Shipped with",
    "from": "from 🇸🇪",
    "facebook": "Facebook page",
    "instagram": "Instagram page",
    "bluesky": "Bluesky page",
    "twitter": "Twitter page",
    "toolNames": {
      "zip-files-online": "Zip Files Online",
      "unzip-files-online": "Unzip Files Online",
      "download-time-calculator": "Download Time Calculator",
      "convert-heic-to-jpg": "Convert HEIC to JPG"
    }
  },
  "pricingToggle": {
    "save": "Save",
    "label": "Payment frequency",
    "yearly": "Yearly",
    "monthly": "Monthly"
  },
  "pricingCards": {
    "trial": "Start a 7-day Free Trial",
    "subscribe": "Subscribe",
    "bestValue": "Best Value",
    "once": "once",
    "month": "/month",
    "due": "{price} due today. Cancel anytime.",
    "save": "Save",
    "year": "/year",
    "billedYearly": "Billed annually at {price}.",
    "locale": "en-US"
  },
  "teamPricing": {
    "button": "Get Started with Teams",
    "month": "/month",
    "users": "users",
    "seat": "/seat",
    "save": "Save",
    "year": "/year",
    "billedYearly": "Billed annually at {price}.",
    "seatsLabel": "Number of users",
    "locale": "en-US"
  },
  "pricing": {
    "quick": "Full access to Quick Transfers",
    "noAccount": "Use without an account",
    "noLimit": "No limit on file size",
    "expires": "Transfers expire when browser tab is closed",
    "noStorage": "No storage",
    "eyebrow": "Pricing",
    "title": "Less to spend, more to send.",
    "free": "Free",
    "freeDescription": "Send files without size limits, with end-to-end encryption. No account needed, but files are only available while your browser tab is open.",
    "quickButton": "Try a Quick Transfer",
    "description": "Plans start at {price} a month when billed annually. Try Starter or Pro free for 7 days. We're independent with no shareholders to pay, so we don't need to charge what the big names do."
  },
  "comparison": {
    "starterPlan": "Starter plan",
    "proPlan": "Pro plan",
    "unlimited": "Unlimited",
    "freeSize": "free file size",
    "e2e": "End-to-end encryption",
    "trackers": "trackers",
    "tracker": "tracker",
    "ownAnalytics": "We use a self-hosted analytics instance on our own server. Your visit is recorded by us and nobody else.",
    "openSource": "Open source",
    "noAi": "No AI training on your files",
    "storage": "Files stored up to 365 days",
    "ownFootnote": "*Quick Transfers are free, unlimited, and offer E2E. We don't bill extra for VAT.",
    "viewPlans": "View & compare plans",
    "wetransferTrackers": "Loads googletagmanager.com, doubleclick.net, googlesyndication.com, google.com, bat.bing.com and DataHog.",
    "wetransferFootnote": "*Starter capped at 300 GB total transfer per month. Price includes {vat}% VAT.",
    "fullComparison": "Full comparison",
    "smashTrackers": "Loads googletagmanager.com (Google Analytics). Your visit and webpage actions are reported to Google when you use the site.",
    "smashFootnote": "*Files over 2 GB queue during peak hours on free. Price includes {vat}% VAT.",
    "eyebrow": "How we compare",
    "title": "How does Transfer.zip compare?",
    "description": "We built Transfer.zip because the popular options were either expensive, restrictive, or quietly training AI on your files.",
    "month": "/mo",
    "billing": {
      "yearly": "billed yearly",
      "monthly": "billed monthly"
    },
    "locale": "en-US"
  },
  "hero": {
    "myTransfers": "My Transfers",
    "github": "Star on GitHub",
    "encrypted": "Data is encrypted",
    "openSource": "Open source",
    "largeFiles": "Send 100GB+ for free",
    "mobileNote": "No size limit, data is encrypted",
    "titleBefore": "Try the",
    "sendAfter": "way to send files.",
    "receiveAfter": "way to receive files.",
    "words": [
      "easiest",
      "fastest",
      "safest",
      "simplest",
      "ethical",
      "private"
    ]
  },
  "upload": {
    "errorTitle": "Oops.",
    "addFiles": "Add some files first ;)",
    "addRecipients": "You did not add any recipient email!",
    "duplicate": "We can't send multiple files with the same name! Try again.",
    "name": "Name:",
    "upgrade": "Upgrade your plan",
    "upgradeRecipients": "to send a file to up to 30 people at once.",
    "starterRecipients": "With the Starter plan, you can only send a file transfer to up to 10 email recipients at once. Upgrade to Pro to send up to 30 emails per transfer.",
    "proRecipients": "With the Pro plan, you can only send a file transfer to up to 30 email recipients at once.",
    "pickFiles": "Pick files",
    "pickFolder": "or select a folder",
    "files": "Files",
    "folder": "Folder",
    "reload": "Reload Page",
    "view": "View transfer",
    "sendMore": "Send more files",
    "free": "FREE",
    "recipients": "Recipient(s) email",
    "addEmail": "Add Email",
    "title": "Title",
    "message": "Message...",
    "settings": "SETTINGS",
    "storageTitle": "Hey big sender...",
    "storageDescription": "Your storage is full. Upgrade your subscription now to send bigger files.",
    "temporaryTitle": "Temporary file-sharing link.",
    "temporaryDescription": "This will create a temporary download link with end-to-end encryption. The link will expire when your browser tab is closed.",
    "keepLinks": "Keep download links for a year.",
    "unlimited": "Unlimited transfers",
    "branding": "Custom logo & branding",
    "emailFeature": "Send files by email",
    "startFree": "Start for free",
    "expires": "Expires",
    "after": "after",
    "getLink": "Get Link",
    "transfer": "Transfer",
    "upgradeTitle": "Keep your files available longer",
    "upgradeDescription": "Free transfers expire when you close your browser tab. Upgrade to keep your download links active for up to a year.",
    "yearLinks": "Links that last up to 1 year",
    "emailDirect": "Send files directly by email",
    "brandingUpgrade": "Custom branding & logo",
    "unlimitedUpgrade": "Unlimited file transfers",
    "later": "Maybe later",
    "locale": "en-US",
    "file": "file",
    "remove": "Remove",
    "moreFiles": {
      "one": "and {count} more file",
      "other": "and {count} more files"
    },
    "tabs": {
      "email": "Email",
      "link": "Link"
    },
    "finished": {
      "email": "Your files were sent!",
      "link": "Your files were uploaded!"
    },
    "expiration": {
      "0": "tab is closed",
      "3": "3 days",
      "7": "7 days",
      "14": "14 days",
      "30": "30 days",
      "180": "6 months",
      "365": "1 year"
    },
    "requestFiles": "Request Files",
    "dropLabel": "Let go to add them",
    "gotIt": "Got it",
    "progress": {
      "failed": "Unfortunately, there was an error.",
      "processing": "Processing files...",
      "of": "of"
    },
    "brandProfile": {
      "icon": "Brand Profile Icon",
      "brand": "Brand",
      "none": "No brand profile",
      "empty": "No brand profiles."
    },
    "defaultErrorTitle": "Something went wrong"
  },
  "request": {
    "copiedLink": "Copied Link",
    "copiedDescription": "The request link was successfully copied to the clipboard!",
    "finished": {
      "email": "Your request was sent!",
      "link": "Your request link was created!"
    },
    "copyRequestLink": "Copy Request Link",
    "view": "View in Dashboard",
    "temporaryTitle": "Temporary file-sharing link.",
    "temporaryDescription": "This will create a temporary link for downloading files, of any size, from other people. The link will expire when your browser tab is closed.",
    "keepLinks": "Unlock links that never expire!",
    "emailFeature": "Receive files by email",
    "receiveLimit": "Receive up to 1TB",
    "getLink": "Get a Request Link",
    "sendInstead": "Send Files Instead"
  },
  "signup": {
    "files": "files",
    "dashboardTitle": "View all your transfers in one Dashboard",
    "extendTitle": "Extend your link's life!",
    "title": "Unlock Better File Sharing",
    "newTabTitle": "Sign in on the new tab.",
    "emailTitle": "Check your email.",
    "planTitle": "Aaaalmost there!",
    "description": "The simplest way to send files on the web.",
    "newTabDescription": "Finish the signin in the new tab.",
    "emailDescription": "Follow the link in the email to finish the sign in!",
    "planDescription": "Pick a plan for your free trial to begin sharing files.",
    "planButton": "Pick a plan",
    "your": "your",
    "readySingle": "is ready to upload.",
    "readyPlural": "are ready to upload.",
    "keepBefore": "Keep",
    "keepAfter": "available for up to a year.",
    "area": {
      "google": "Sign In with Google",
      "or": "OR",
      "emailPlaceholder": "name@example.com",
      "emailButton": "Sign In with Email",
      "magicLink": {
        "expired": "This sign-in session expired. Request a new link.",
        "signedIn": "You're signed in",
        "dashboard": "Go to dashboard",
        "otherBrowser": "The sign-in email was opened on a different browser. Enter the 6-digit code shown there to finish signing in here.",
        "verify": "Verify and sign in",
        "differentEmail": "Use a different email",
        "sent": "An email has been sent to your inbox!",
        "waiting": "Waiting for you to open the link...",
        "open": "Open"
      }
    }
  }
};
