name: docker-ci

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '**/README.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push signaling-server
        uses: docker/build-push-action@v2
        with:
          context: signaling-server/.
          file: signaling-server/Dockerfile
          push: true
          tags: l4rm4nd/transferzip:signaling-server
          platforms: linux/amd64
      -
        name: Build and push web-server
        uses: docker/build-push-action@v2
        with:
          context: web-server/.
          file: web-server/Dockerfile
          push: true
          tags: l4rm4nd/transferzip:web-server
          platforms: linux/amd64          
